/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.app2;

public class AppTest {
  //    @Test public void appHasAGreeting() {
  //        ServerApp classUnderTest = new ServerApp();
  //        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
  //    }
}
